"use client";

import "./globals.css";
import { Inter, Prociono } from "next/font/google";
import { Providers } from "./providers";
import Footer from "@/components/footer";
import { useState, createContext } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };
export const AppContext = createContext();

export default function RootLayout({ children }) {
    const [account, setAccount] = useState("");

    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <AppContext.Provider value={{ account, setAccount }}>
                        {children}
                        {/* {cloneElement(children, { account, setAccount })} */}
                        <Footer />
                    </AppContext.Provider>
                </Providers>
            </body>
        </html>
    );
}
